server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone : http://localhost:7001/eureka,http://localhost:7002/eureka
ribbon:
  eureka:
    enabled: true

#负载策略
MICROSERVICECLOUD-DEPT: #服务名
   ribbon:
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule